### ISSUE TITLE
emerald server start with args --host=127.0.0.1 --port=1920 error.

### ISSUE THREAD

**Issue by yourihua** [ETCDEVTeam/emerald-cli#126]
![image](https://user-images.githubusercontent.com/1717368/42254911-aa6c318c-7f7b-11e8-82a5-ee554102bcc6.png)

**Comment by yourihua** [comment]
version v0.22.0

**Comment by r8d8** [comment]
@yourihua, please use args without flags.
```shell
$ emerald server 127.0.0.1 1920
```
