### ISSUE TITLE
raw pk from cli option

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-cli#39]
Allow to pass a raw PK from command line.

```
emerald-cli --raw 0x8AB57394868C31248C3A3D22DA61E6D436D3638413FB33724514E
emerald-cli --raw-file ./pk-in-hex.txt
```

Should be available as alternative to a pk stored in key storage, for sending/signing a transaction

**Comment by r8d8** [comment]
`--raw <pk>`  will resist in a history, better to omit this, imho
Or we can add read from `stdin`

**Comment by splix** [comment]
Let's read from stdin if `-` passed, that's also a solution to both use cases. Like: 
```
cat pk-in-hex.txt | emerald-cli --raw -
```
