### ISSUE TITLE
MissingFieldError("crypto"): should check for "Crypto" too

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/emerald-cli#45]
```
~/dev/etc/emerald-cli master= ⟠ emerald import --chain=mainnet path/to/key_encrypted
[ERROR]	Command execution error: Invalid keystore file decoding: MissingFieldError("crypto")
~/dev/etc/emerald-cli master= ⟠ cat path/to/key_encrypted
{"version":3,"id":"asdf-asdf-asdf-asdf-asdf","address":"0x539blahblah","Crypto":{"cipher [...]
```

`sed -i 's/Crypto/crypto/' path/to/key_encrypted` and all is ok. I guess all key/values should be case insensitive?

**Comment by r8d8** [comment]
@whilei , actually we can't handle this because  JSON deserialization is a case sensitive, it counts `crypto` and `Crypto` as 2 different fields.

**Comment by splix** [comment]
@r8d8 but you can convert it to lower case _before_ parsing json

**Comment by r8d8** [comment]
It will require reqexp, I just can't convert whole file.
Ok, I think it wouldn't reduce perfomance too much

**Comment by whilei** [comment]
Can just check `Crypto` and/or `crypto` instead of only one JSON key?

**Comment by r8d8** [comment]
yeap, but even not greedy regexp will parse half of json till it reaches `crypto`
Lets  make it and solve any bottleneck later, if they will occur at all.

**Comment by splix** [comment]
maybe there is a way to use a simple string replacement, w/o regexp? anyway, it wouldn't be a bottleneck, as it used only once during initial import
