### ISSUE TITLE
Command to remove account

### ISSUE THREAD

**Issue by gagarin55** [ETCDEVTeam/emerald-cli#68]
Which command is suitable to remove account from key storage ?

**Comment by r8d8** [comment]
`emerald-cli` doesn't have command for account deletion. We was concernd that user can delete account and loose his ethers.

**Comment by splix** [comment]
There was a command to hide account, can be used instead.

**Comment by splix** [comment]
We should add a command for deletion I think

**Comment by gagarin55** [comment]
Yes, we need console command for removing account data but showing warning and asking additional confirmation from user
